apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-api-token
    namespace: cloudflare-ddns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:uFdJLLM7CpJ/8ONQ2gGZtPTsHSxbUotw8kaWvZ7pdVCNVNOgAeiSwXXGFQd0B60qM36c98k=,iv:p3nC+9FYfm1MyejgPzcODnOkXTyQphqXN+s1XhACqS8=,tag:0qZosoVgo0gPQ1VFIJVjPA==,type:str]
sops:
    age:
        - recipient: age1lv9al5v7egq73rz56c9y6vhtwt88rzahyzt5u7r69864wt9vze3qa7mhz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMXcxbFpjOFM0emtWcWxn
            cVd1YXY1UEQvNExBYlEwK1lJNC9yeEdaVVNFCnNQeVNxTmlhdTdCaURiYTJOZ2Nm
            cHBKWG51YWdrTWJ1WHA2NzEzZlhYbmsKLS0tIGRUSE9iejJiUCtFSDFsKzVWWW9i
            VEVYdnlKK3ExNFhRLzRzUWtQNWtwNTgKu0hfm2Q0t29BSDNHCznkOiCVbdJB1mEX
            oZjEMACMHkWod6L2aAUvtwUhK5i3R6WWhB8DQWtDf+fQ+8mUw35LLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T08:35:38Z"
    mac: ENC[AES256_GCM,data:3ELsCxkpgIIVaW2nIE9b7H4D5gLETs5etIqcWsw08jxV0Oct0JyL6MWwpPZFL5AHjUrKOOx4Q0Ue2Nou6eBWIQYvspt8G/z7X6CAKmkGJoNjDIDAAk95jAZoz5CVRPLUwHvVrmLCkIlZC5Mx+xeD7lURSjm6KGRjVzMSihvlTJU=,iv:6Wrc/REovcXIdiNxZrmWFpuroFGsp2mxSS6urjGfNDM=,tag:sWUZKm4oXoCWG5pU3FUUNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
