apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: favonia/cloudflare-ddns:latest
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-dns-api-token
                  key: api-token
            - name: DOMAINS
              value: budget.disablak.xyz,home.disablak.xyz,cloud.disablak.xyz,logs.disablak.xyz,argocd.disablak.xyz,jellyfin.disablak.xyz
            - name: PROXIED
              value: "false"
            - name: IP6_PROVIDER
              value: "none"
            - name: UPDATE_CRON
              value: "*/5 * * * *"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
