apiVersion: v1
kind: Secret
metadata:
    name: quake3-rcon
    namespace: quake3
type: Opaque
stringData:
    rconpassword: ENC[AES256_GCM,data:BhlzGS7MRteLSQWI6J6msAzj/ugsUb7eigldehMcskE=,iv:HiubmhMjHPrb88kVeZcdU8B0aGibHkjAoR1NJTXzmnY=,tag:Qq34ZwWeh96vEhH1/j84DA==,type:str]
sops:
    age:
        - recipient: age1lv9al5v7egq73rz56c9y6vhtwt88rzahyzt5u7r69864wt9vze3qa7mhz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcW9pYThhSGRvd0pueW43
            c2oySjFPZ0lYd3BkekVWeGNrWEc0SmVYOTFRCkR1WjhqbHQyMWdocERyZXB2aExu
            RkhTSHVRWE5iYjZjbVBTNFBIdnNybVEKLS0tIEFFTVdKN0VKMStPQmtyUklZak42
            dTkxSmY0UTdET09nUDJNUnZ2eFdmYlEKfH9qFpDCV4MulORp5j+CQkTGpB7+1VUO
            +IWQ3Zt2gQiaFzAuufOxk2HcFFs1Kmc0tFWuK+KEy1VZ9CGGoNiAkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T10:57:20Z"
    mac: ENC[AES256_GCM,data:daeuNrfZ9eHWkCiulWCQWgwUF23fuwCuHqxco5fcn706nVoXj7SQ+2s2khqbiMbWiTadu3ZMXk1FL0WudFn8QLHfuNcGnsj9/ssUP7BItBepoxTIwlmKNMNZqA1pt1BxE6bQpsD8XWiDoFtP4AHrYt/9N67t/V/RfW+G+8HMbFA=,iv:5459SpJrz2uzEv+RfHk5QixOuGX8m3u1rsS1LSndvTM=,tag:AJnQp1Fhx0svdfVMrPiICA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
