apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ArLjUGeRiGo=,iv:UqR96YlHSm2hm9UVxUScIn0EkozCyVBU+DaR0iRjRbg=,tag:gBPpzawlgKnZTQ1+Zdg9nQ==,type:str]
    password: ENC[AES256_GCM,data:qYfIUm9b9+esztmOFIMQaA==,iv:j4xSLFHr23y3UYyUe6zaWjtYMDJXIxPQjTSDvBBRg5I=,tag:6s+de0uKUTgqZFDacNRVOQ==,type:str]
sops:
    age:
        - recipient: age1lv9al5v7egq73rz56c9y6vhtwt88rzahyzt5u7r69864wt9vze3qa7mhz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a2F0aGV6QTdVTERvdXU0
            VlZuTkk3OSsrZU5yako4SHFFdUxaTkJZSGk0ClFJSXdRUk5qb3JwV09yQ3AxdmEx
            L1RSSEcvb2t5c2w0aEZSemJmSERmQXcKLS0tIGZWbnBLVG1MekFkdVJXblpyUFBF
            Mmx1MmlFMUZ2SDFhT2lUcTExOXN0ZUUK+tCHmj0v82C9b+6ftwGSP2kHZsXJNMs2
            HU2rbeRuy/9auC+0+J7YusO+Hry7hQ3J0oljr5ilkE1iAR+D31QRNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T08:37:21Z"
    mac: ENC[AES256_GCM,data:GZ7YfIpNQTNsXmddcHgCcQM5SY4zvE1Hekfue2+bVfRWuCF6XNbs9Egt6zVnNN8OhRxENEp0is+w6snylhLiJhXeMTjseUDoWJ1UfvlrFTZpdMjdHoL5hxof0VDvysTCYSLTnwqSDwbdybhw/PZazXsIefn9cqDF26HDAsACXgM=,iv:cFROBCJWZ4RzoJlCh/FIJcXjZnCRrDo0RtZOpfOxUyU=,tag:rjLBughSrXjEoFUVnoHUFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
