apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db
    namespace: nextcloud
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:0wVR0Ef7ATff1LPsGMoT3A==,iv:G6GIHJP65B/rKopiHyv3FrRE1ahg5EsEvaXZSYh9bSQ=,tag:Jx8n1MHbxRZs0DUtv/75VQ==,type:str]
    root-password: ENC[AES256_GCM,data:Y1HLoSTGeRobivluD54Tig==,iv:j+X7oei2ToSvF0+moQz93/7en/U9enhX9ich/t0QWNA=,tag:kYCcvM6i/oBygJcMZ8FPXA==,type:str]
sops:
    age:
        - recipient: age1lv9al5v7egq73rz56c9y6vhtwt88rzahyzt5u7r69864wt9vze3qa7mhz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVVNXRUppaklEaVo5L1J6
            Z3EwbElFOXY3eUJaSWRMM2pPVjRnRzVCVEJvCmFVS28xR2JkVVJFb0F3ZU9DdmFz
            WEpIbHROQ2szaGRwbDgxZHlIeDRoYXcKLS0tIEhCZGVnaGVmWWdqelE1ODdMQjBB
            UHA3Mmp0YlhJUnhnQzJ2aEd2cHdodzgKWGmCAQd5eRV4sawF0zgzOs7FKYsBPiub
            8YttgtPYmCyjwW16gpH/pGTVxnjdakAsups8sYUAsLe8lyYS0BcTOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T08:37:25Z"
    mac: ENC[AES256_GCM,data:IVjylUXk3xFF43eSTE5/zv5RRsCgkhoJSYogWDIGaetEF7olzeDmG/R+6UrRQEzLl58Ayx9nkT6dLLc6dQUNYmBDPl2Q/p1hMfu7Yv0eNO+Ett8Iol17HGrW/3tDNliBaxnOtQf+G8Of7IzdIByw7mR2MgfDzNtawB7PdpsJVQk=,iv:IfsRof5hxxZoRoVjGUrCB0NeRQWOfftDdTSzwvg+7Sk=,tag:ugbVrRD/FzAPa1UwiWAJgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
