apiVersion: v1
kind: Secret
metadata:
    name: homepage-basic-auth
    namespace: homepage
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:EYB/dfkH1UbDnYnlXJgqg7QQGLGczWfJ4yRh9yN56O3rcpNg8ae+CUPPL6G7VXfC46MBbbg/4gg2XlvJKGSSBX3AVFbe,iv:v/0rFK9G/2EgJhVbjEIeIm49vT8dMVAtToLYFWX8iiQ=,tag:AbFadXlpIMh7cIKvQFqvWA==,type:str]
sops:
    age:
        - recipient: age1lv9al5v7egq73rz56c9y6vhtwt88rzahyzt5u7r69864wt9vze3qa7mhz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRXphQUk3QkI1ODlSdytS
            aytpamNWN3hoNG9ZN1JJTHJjWnVxQjhiVXdZCnZQVHdkdlo3eUU5UVhTM214RkdF
            eUV3cTVnWGlGbTdtVnRrUlUvQ2JlK0kKLS0tIDRCUisvbVR6UWlCODNtQjBNemt5
            NE03c0I4K2UzWmxpSWc5UzF3bmxGYWMKgmGkk29eSM6eKpMz30bOWQK2uOBA5YMZ
            zlZtZaB+AfTJ0IZn0sPq3N0TUHjSmLQxpSeu0PE50SBmJ/+hfPeyMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T08:31:43Z"
    mac: ENC[AES256_GCM,data:IAuFsD6kZ9hF4Zpu+0a6ntSTNVpYOifNuXjqQ6ff53kCSkmWaY6wwLyVVb3F5mtbyw021qftz2dXA1EuC+rOnC9pqK65sgtefKMIuaA2KzymkJl58OaHzg1HJ9ljYg3P42px0wqX7+5O3t1tlKkSU5QiOP43Bek29Alt03PiVUY=,iv:5IriUfu0LAfW70UwHr0wvX6ZY/EyG/PIiRAt8vdDMNk=,tag:4l3TAi49QN0xJLP9EZZ+/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
