apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home
    theme: dark
    color: slate
    headerStyle: clean
    background:
      image: https://images.wallpapersden.com/image/download/beautiful-landscape_bGplZWyUmZqaraWkpJRnamtlrWZpaWU.jpg
      blur: sm
      saturate: 90
      brightness: 90
      opacity: 90
    layout:
      Kubernetes:
        style: row
        columns: 4
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  services.yaml: |
    []
  bookmarks.yaml: |
    []
  widgets.yaml: |
    - openmeteo:
        label: Vinnytsia
        latitude: 49.2331
        longitude: 28.4682
        timezone: Europe/Kyiv
        units: metric
        cache: 5
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "disablak"
        nodes:
          show: false
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
