apiVersion: v1
kind: Secret
metadata:
    name: victorialogs-basic-auth
    namespace: victorialogs
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:BoKE46OlZyJisgBwJqKkoUPw6WctrAUDViQmrxSaBU96YLNDiZZrfx8TiG4Gqn5aPdl5cDnWZesbm/Oo/zaIv3JS,iv:0Gi9ar9sHvT0/4lbpis9gng+qaDftEXII9SM3Ltw4cA=,tag:GY/o/ge+jhWM8AVgEdTUqQ==,type:str]
sops:
    age:
        - recipient: age1lv9al5v7egq73rz56c9y6vhtwt88rzahyzt5u7r69864wt9vze3qa7mhz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSVlYK3hBaXAzbG4velJT
            S3piUExxZENweFE4UnhQYmlUM1ljKzZxekF3Cm4xMSt0NlFqM1RXQ0hpbDN1U08z
            aldSVm5vOGNOUGVEMnIvKzBTSmtEeUEKLS0tIDlXdmIyVkJIS0N4bmtlNjlvaTh6
            eUtvWnpRQ0ptK2VFaUZ5QVlsS2VCQTQKUea1p/jK+oz0a6P9hYduU5U/PCXzj4Lj
            OH8jhb+fOV5bnjxAreh2xmuERY4WRwHiYalo/2tEmxkJc64cbKXi4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T19:23:10Z"
    mac: ENC[AES256_GCM,data:ihnzJdj20EXCuqIsSYtPdyv8AQTZXZuqprcye+/SigfFxkE7i/AxLZwo5z4jpBh4DOUGmdukER+omayrBwpHkXIpyricOPvmRZUrQRxswxWIKbng+O3m+oXi+RHztzdoCJuMM132crlmamPG8nVTN0zZxiVGI6y+oaosISLysOQ=,iv:aWj3ULmeY69bs2D/A0JsyYhDIO2TN42VaUSG4WUcVXQ=,tag:HH5xkU4I6a7lDtpcyHcnoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
