apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-budget
  namespace: actual-budget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Actual Budget"
    gethomepage.dev/icon: actual-budget.svg
    gethomepage.dev/href: https://budget.disablak.xyz
    gethomepage.dev/group: Apps
    gethomepage.dev/pod-selector: "app=actual-budget"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - budget.disablak.xyz
      secretName: actual-budget-tls
  rules:
    - host: budget.disablak.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: actual-budget
                port:
                  number: 5006
