apiVersion: v1
kind: Secret
metadata:
    name: argocd-basic-auth
    namespace: argocd
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:11IjS8GZ1oChxeS52Nge1P6FWcFEZHzv8dgnWPOKJo3bYrYbbwcfaUkXOx5h7PTL5ghHj59UqiNaD9eQbW/9D/ih,iv:0zleAZ6bXZoFJBoLZaBhGhXfKKUME7wXFSlK3slNc+E=,tag:bFXoNqwqSAHEmp5aSBJIAQ==,type:str]
sops:
    age:
        - recipient: age1lv9al5v7egq73rz56c9y6vhtwt88rzahyzt5u7r69864wt9vze3qa7mhz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbndVa3ViUEVFZzdRN0RI
            WFJMSkFLZksvWUhiNk1kdFZGcCtkRFBGNndvCnJURTcxaFdtODZVZHU3UXNqTzcy
            Q29rQ0Y1cDBuelRZR1FNRW4yaXZoVGcKLS0tIE1EVE0vYVNNekFCMHc5N1BvYnN5
            YlVMZzNLU2toeEd0d3M3emZuMkpsSGsKnYMxnusTf4fL6cTmSpsBY5wJB0Ecm95O
            +1wyeSvmVH28MAPc5KxfyQeMgqrXpZ8FrFRt9zZfhjLlsdxRao6F6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T18:49:59Z"
    mac: ENC[AES256_GCM,data:E9rpxBMARN70hSpKGTOgCRqbBEvjUoNt4f31Yl4lNKtqOTnv7coPk0ZeL0VTktM4h6+BrFivcqAK5llZKvDPXsrThh5D9vxOPRkQYAufpmbqeX+4uu2jOusJc9+tJBO6rcqZLVAT5BMm9N8cCMXfsjZgOfFEpQ3hIqxJjiD4XkE=,iv:FMmaXgylC/uZRjLhZZ+jwIBvDCTWDEH6zKVWCZEhEho=,tag:B44Y8KZAGutDrIeMGSGMwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
